### ISSUE TITLE
LilyPond cannot be found

### ISSUE THREAD

**Issue by hegelkoenig** [jperon/lyluatex#204]
Hello,

I heard of this package in a seperate issue for TeXstudio and it seems to be exactly what I am looking for. Problem is, TeXstudio can't seem to find LilyPond in order to use it.

[https://github.com/texstudio-org/texstudio/issues/236](url)

I added LilyPond to the environmental path, as shown here [http://lilypond.org/windows.html](url). Unfortunately, the error persists. Can the package be tailored for Windows users, or at least some form of hint given, how Windows users can use this package?

```
Der Befehl "lilypond" ist entweder falsch geschrieben oder konnte nicht gefunden werden.

...ta/Local/Programs/MiKTeX 2.9/tex/latex/base/ltluatex.lua:109: 
Module lyluatex Error: LilyPond could not be started.
(lyluatex)             Please check that LuaLaTeX is started with the
(lyluatex)             --shell-escape option, and that 'program'
(lyluatex)             points to a valid LilyPond executable.
(lyluatex)             on input line 35
```

**Comment by dbitouze** [comment]
Did you try from the command line? For this, open your file (say `document.tex`) in TeXstudio and visit Tools → Open Terminal. In the terminal, run:
```bash
lualatex --shell-escape document
```
What's the result?

**Comment by hegelkoenig** [comment]
Exactly the same

**Comment by jperon** [comment]
I'll have a glance in a Windows VM when I've time. Meanwhile, you could use this workaround : use `lyluatex` with option `program` pointing to your lilypond executable, for example : 

```latex
\usepackage[program=/my/path/to/lilypond]{lyluatex}
```

**Comment by hegelkoenig** [comment]
My path to lilypond is:
`C:\Program Files (x86)\LilyPond\usr\bin`

LaTeX seems to be having trouble with the spaces. Precisely which argument do I have to give to `program`? I've tried the following permutations:

`C:/Program Files (x86)/LilyPond/usr/bin`
`"C:/Program Files (x86)/LilyPond/usr/bin"`
`{"C:/Program Files (x86)/LilyPond/usr/bin"}`
`/Program Files (x86)/LilyPond/usr/bin`
`"/Program Files (x86)/LilyPond/usr/bin"`
`{"/Program Files (x86)/LilyPond/usr/bin"}`

**Comment by uliska** [comment]
I have no real clue about Windows here but you have omitted the permutation that I would have recommended:
```
program={C:/Program Files (x86)/LilyPond/usr/bin}
```
enclosing the "offending" code in curly brackets, but with no further quotes.

[EDIT:] *And* (more importantly): I *think* you have to point to the *executable*, not to the path, which would probably be

```
program={C:/Program Files (x86)/LilyPond/usr/bin/lilypond-windows.exe}
```

**Comment by jperon** [comment]
@hegelkoenig Sorry for the late reply, but could you please test from branch [fix-204](https://github.com/jperon/lyluatex/tree/fix-204), please ?

**Comment by hegelkoenig** [comment]
@jperon 

Tested it. Replaced the MiKTeX version of lyluatex with the one provided by your link. Still no banana …

`
\documentclass[a4paper, 11pt]{article}

\usepackage{lyluatex}
%\usepackage[program={C:/Program Files (x86)/LilyPond/usr/bin}]{lyluatex} % Doesn't work
%\usepackage[program={C:/Program Files (x86)/LilyPond/usr/bin/lilypond-windows.exe}]{lyluatex} % Doesn't work either

\begin{document}
	This is a MWE.
	
	\begin{lilypond}
		c d e 
	\end{lilypond}
\end{document}
`

**Comment by jperon** [comment]
Could you please try again with last version (master branch) ? On my windows vm (with TeXLive, not MiKTeX), these options work : 

```
program={C:/Program Files (x86)/LilyPond/usr/bin/lilypond-windows.exe}
program={C:/Program Files (x86)/LilyPond/usr/bin/lilypond-windows}
```

(And the path is case-insensitive).

**Comment by hegelkoenig** [comment]
Tried it. Same thing.

```
\documentclass[a4paper, 11pt]{article}

\usepackage[program={{{C:/Program Files (x86)/LilyPond/usr/bin/lilypond-windows}}}]{lyluatex} 

\begin{document}
	This is a MWE.
	
	\lilypond{ c' d' e' } 
	
\end{document}
```


Result:


```
Prozess gestartet: lualatex.exe -synctex=1 -interaction=nonstopmode --shell-escape "test".tex

Der Befehl "C:/Program" ist entweder falsch geschrieben oder konnte nicht gefunden werden.

Prozess endete mit Fehler(n)
```

**Comment by jperon** [comment]
Just in case, but did you update *both* `lyluatex.sty` and `lyluatex.lua` ?

**Comment by hegelkoenig** [comment]
Yes

**Comment by jperon** [comment]
So line 895 must be : 
```
local cmd = '"'..self.program..'" '..
```

If it is, please check, at the beginning of compilation messages, that the right `luatex.sty` is called (in case you'd have an old one somewhere). Another check you could do is `kpsewhich lyluatex.lua` (or it's MiKTeX equivalent), and see wether it points to the right path. Given the error message (`Der Befehl "C:/Program" ist entweder falsch geschrieben oder konnte nicht gefunden werden.`), I'm fairly sure you have an old `lyluatex.lua` somewhere in your distribution, and it gets called instead of the new one.

Normally, putting `lyluatex.sty` and `lyluatex.lua` in the same folder that your main file should ensure they get called.

**Comment by hegelkoenig** [comment]
Line 895 is indeed `local cmd = '"'..self.program..'" '..`

From the log file:

```
("C:/Users/Marcus Arndt/AppData/Local/Programs/MiKTeX 2.9/tex/lualatex/lyluatex
/lyluatex.sty"
Package: lyluatex 2018/03/12 v1.0b
```

… which is exactly where I copied the new files from your master branch.

**Comment by jperon** [comment]
And is there `kpsewhich` in MiKTeX, to ensure `lyluatex.lua` is the good one ?

**Comment by hegelkoenig** [comment]
If I search for it in the MiKTeX console the package `miktex-kpathsea-bin-x64-2.9` shows up. I have no idea what it means or how it works though ...

**Comment by jperon** [comment]
Within TeXLive, you just have to type `kpsewhich FILE_YOU_LOOK_FOR` ; I guess it must be the same on MiKTeX ?

**Comment by jperon** [comment]
Meanwhile, adding quotes around the path should do the trick :
`program={"C:/Program Files (x86)/LilyPond/usr/bin/lilypond-windows.exe"}`

**Comment by hegelkoenig** [comment]
There is no command line in MiKTeX in which I could type something …
Quotes don't work, unfortunately.

**Comment by jperon** [comment]
So that must be a different behavior between MiKTeX and TeXLive, though it's quite weird.

Perhaps I'll try installing MiKTeX to investigate, but that won't be before 10 days.

**Comment by hegelkoenig** [comment]
Ok tried that. Points to the same file.
`C:/Users/Marcus Arndt/AppData/Local/Programs/MiKTeX 2.9/tex/lualatex/lyluatex
/lyluatex.sty`

Okay. Thanks for your help. Keep me posted :)

**Comment by hegelkoenig** [comment]
Just a thought …

MWE:
```
\documentclass[a4paper, 11pt]{article}

\usepackage[program={{{C:/Program Files (x86)/LilyPond/usr/bin/lilypond-windows.exe}}}, debug=true]{lyluatex} 

\begin{document}
	This is a MWE.
	
	\lilypond{{ c' d' e' }} 
	
\end{document}
```

The error message that now shows up:


```
Module lyluatex Info: Command:
(lyluatex)            "C:/Program Files (x86)/LilyPond/usr/bin/lilypond-windows.
exe" -dno-point-and-click -djob-count=2 -dno-delete-intermediate-files -I "E:\Kl
avierlehre\06_Eigenmaterial\Testdokument/" -I "E:\Klavierlehre\06_Eigenmaterial\
Testdokument/" -o "tmp-ly/db2a4a1730071dcf1fa5426557492a6b" tmp-ly/db2a4a1730071
dcf1fa5426557492a6b.ly 2>&1 on input line 8
...ta/Local/Programs/MiKTeX 2.9/tex/latex/base/ltluatex.lua:109: 
Module lyluatex Error: 
(lyluatex)             LilyPond failed to compile the score.
(lyluatex)             Please check the log file
(lyluatex)             and the generated LilyPond code in
(lyluatex)             tmp-ly/db2a4a1730071dcf1fa5426557492a6b.log
(lyluatex)             tmp-ly/db2a4a1730071dcf1fa5426557492a6b.ly
(lyluatex)             
(lyluatex)             on input line 8
```

Contents of the .log file:

`Die Syntax fr den Dateinamen, Verzeichnisnamen oder die Datentr„gerbezeichnung ist falsch.`

Are the backward slashes (`E:\Kl
avierlehre\06_Eigenmaterial\Testdokument/`) at fault? How would one remove them?

**Comment by uliska** [comment]
@hegelkoenig Is this still a thing?

If yes, could you please also provide the content of the (or a new) `.ly` file to inspect. If no, we could close the issue.

**Comment by jperon** [comment]
I'd like to try MiKTeX on a VM before closing; but I have to fix problems I have with my emulator before.

**Comment by hegelkoenig** [comment]
There is no `.ly` file That's kinda the point of the exercise ...
I can work around it at the moment by compiling a `.ly` file and inserting it as a `.pdf `, but would much prefer to be just be able to type and compile directly in TeXStudio.

MWE:

```
\documentclass[a4paper, 11pt]{article}

\usepackage[program={"C:/Program Files (x86)/LilyPond/usr/bin/lilypond-windows.exe"}, debug=true]{lyluatex} 

\begin{document}
	This is a MWE.
	
	\lilypond{{ c' d' e' }} 
	
\end{document}
```

**Comment by jperon** [comment]
@hegelkoenig Could you please try adding this new line just after line 813 in `lyluatex.sty` (providden you have the last version on the repository), then try again compiling your document:

```lua
    if os.type == 'windows' then cmd = '"'..cmd..'"' end
```

**Comment by jperon** [comment]
@hegelkoenig Excuse me, this isn't in `lyluatex.sty`, but in `lyluatex.lua`.

**Comment by jperon** [comment]
@hegelkoenig Could you please try with branch [fix-204](https://github.com/jperon/lyluatex/pull/249), please ? I think it should fix this bug.

**Comment by jperon** [comment]
I've quite extensively tested it, and merged. If it doesn't work for you, please feel free to re-open it.

**Comment by fabianmoss** [comment]
I am having very similar problems. I am using MiKTeX 2.9 on Windows 10.
Using the same MWE, I get the following error message and I am not really sure what to make of it:

```
Module lyluatex Warning: The score doesn't contain any music:
(lyluatex)               this will probably cause bad output. on input line 12
...ta/Local/Programs/MiKTeX 2.9/tex/latex/base/ltluatex.lua:109: 
Module lyluatex Error: 
(lyluatex)             LilyPond failed to compile the score.
(lyluatex)             Please check the log file
(lyluatex)             and the generated LilyPond code in
(lyluatex)             tmp-ly/df4f5b0d087241219c7b25eec6aff4fb.log
(lyluatex)             tmp-ly/df4f5b0d087241219c7b25eec6aff4fb.ly
(lyluatex)             
(lyluatex)             As the input code has been automatically wrapped
(lyluatex)             with a music expression, you may try repeating
(lyluatex)             with the `nofragment` option.
(lyluatex)             on input line 12

stack traceback:
	[C]: in function 'error'
	...ta/Local/Programs/MiKTeX 2.9/tex/latex/base/ltluatex.lua:109: in function <.
..ta/Local/Programs/MiKTeX 2.9/tex/latex/base/ltluatex.lua:108>
	(...tail calls...)
	.../Local/Programs/MiKTeX 2.9/scripts/lyluatex/lyluatex.lua:555: in method 'che
ck_compilation'
	.../Local/Programs/MiKTeX 2.9/scripts/lyluatex/lyluatex.lua:1179: in method 'wr
ite_latex'
	.../Local/Programs/MiKTeX 2.9/scripts/lyluatex/lyluatex.lua:1108: in method 'pr
ocess'
	[\directlua]:1: in main chunk.
\ly@compilescore ...directlua {ly.score:process()}
                                                  
l.12 	\end{lilypond}
                  
? 

Underfull \hbox (badness 10000) in paragraph at lines 12--13

 []

[1

{C:/Users/fabianmoss/AppData/Local/MiKTeX/2.9/pdftex/config/pdftex.map}]
(./lilytest.aux))
```

**Comment by CheeseTurtle** [comment]
Has anyone determined how to fix this? Are manual fixes still necessary?

**Comment by hegelkoenig** [comment]
Still isn't working for me...
I've kinda given up and am doing everything manually.

**Comment by CheeseTurtle** [comment]
What do you mean, manually? I'd really like to use this package to help with the typesetting of my thesis. :/

**Comment by hegelkoenig** [comment]
As in, I write my own .ly files, compile them, fiddle around until they're the right size, and insert them with \includegraphics

**Comment by ahanuban** [comment]
@CheeseTurtle @hegelkoenig did either of you figure this out? I'm having the exact same issue now, 3 years later.

**Comment by jperon** [comment]
@ahanuban May you please try with #300 ? I didn’t have time to check it myself (as I don’t have a Windows computer), but I’d be interested if you could test it.
